### ISSUE TITLE
Fix for 404 Exception/Warning if file is missing on Fritzbox

### ISSUE THREAD

**Issue by bufemc** [blacksenator/fritzsoap#1]
Hallo, anbei ein funktionierender Workaround, um Exceptions/Warnings zuverlaessig zu unterdruecken, falls die entsprechende XML-Datei auf der Fritzbox nicht existiert. Ich hatte auch in der Doku zu simplexml_load_file selbst geschaut, und dort alle moeglichen Parameter durchprobiert, doch keiner aenderte etwas an dem merkwuerdigen Verhalten, das obwohl ein @ im Code davor steht, trotzdem ein Fehler geworfen wird. Ich habe den Code-Fix auch in einen eigenen Branch gepackt und versuche es mal rueberwachsen zu lassen. Warum das mit substr? Weil derzeit die Fritzboxen noch HTTP/1.0 verwenden, aber wer weiss ob es uebermorgen dann 1.1 ist.

```
    private function getServiceXML(string $xmlFile, string $node): array
    {
        $result = [];
        $file_headers = @get_headers($xmlFile);
        if ($file_headers !== false && substr($file_headers[0], -13) != '404 Not Found') {
            $xml = @simplexml_load_file($xmlFile);
            if ($xml != false) {
                $xml->registerXPathNamespace('fb', $xml->getNameSpaces(false)[""]);
                $result = $xml->xpath("//fb:$node");
            }
        }

        return $result;
    }
```

EDIT: added additional check if headers could be retrieved

Pull Request: https://github.com/blacksenator/fritzsoap/pull/2

**Comment by blacksenator** [comment]
improve error handling and improved fault tolerance implemented;

@bufemc : many thx for stressing this
